### ISSUE TITLE
KeyError: 'template_paths' on M1 Mac, Big Sur 11.2

### ISSUE THREAD

**Issue by halloyz** [betatim/notebook-as-pdf#27] opened 2021-04-07 12:41 UTC
I recently upgraded my old macbook where pdf export worked absolutely fine. Installed the same way on my new m1 mac mini, now the option of exporting does not appear in jupyterlab and when trying to export via terminal I get the following error:

```
Traceback (most recent call last):
  File "/Users/User/opt/anaconda3/lib/python3.8/site-packages/traitlets/traitlets.py", line 535, in get
    value = obj._trait_values[self.name]
KeyError: 'template_paths'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/User/opt/anaconda3/bin/jupyter-nbconvert", line 11, in <module>
    sys.exit(main())
  File "/Users/User/opt/anaconda3/lib/python3.8/site-packages/jupyter_core/application.py", line 270, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/User/opt/anaconda3/lib/python3.8/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.start()
  File "/Users/User/opt/anaconda3/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 350, in start
    self.convert_notebooks()
  File "/Users/User/opt/anaconda3/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 518, in convert_notebooks
    cls = get_exporter(self.export_format)
  File "/Users/User/opt/anaconda3/lib/python3.8/site-packages/nbconvert/exporters/base.py", line 102, in get_exporter
    if getattr(exporter(config=config), 'enabled', True):
  File "/Users/User/opt/anaconda3/lib/python3.8/site-packages/notebook_as_pdf/__init__.py", line 204, in __init__
    super().__init__(config=with_default_config, **kw)
  File "/Users/User/opt/anaconda3/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py", line 325, in __init__
    super().__init__(config=config, **kw)
  File "/Users/User/opt/anaconda3/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 114, in __init__
    self._init_preprocessors()
  File "/Users/User/opt/anaconda3/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py", line 491, in _init_preprocessors
    conf = self._get_conf()
  File "/Users/User/opt/anaconda3/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py", line 507, in _get_conf
    for path in map(Path, self.template_paths):
  File "/Users/User/opt/anaconda3/lib/python3.8/site-packages/traitlets/traitlets.py", line 575, in __get__
    return self.get(obj, cls)
  File "/Users/User/opt/anaconda3/lib/python3.8/site-packages/traitlets/traitlets.py", line 538, in get
    default = obj.trait_defaults(self.name)
  File "/Users/User/opt/anaconda3/lib/python3.8/site-packages/traitlets/traitlets.py", line 1578, in trait_defaults
    return self._get_trait_default_generator(names[0])(self)
  File "/Users/User/opt/anaconda3/lib/python3.8/site-packages/traitlets/traitlets.py", line 975, in __call__
    return self.func(*args, **kwargs)
  File "/Users/User/opt/anaconda3/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py", line 518, in _template_paths
    template_names = self.get_template_names()
  File "/Users/User/opt/anaconda3/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py", line 608, in get_template_names
    raise ValueError('Unsupported mimetype %r for template %r, mimetypes supported are: \n\t%s' %\
ValueError: Unsupported mimetype 'application/pdf' for template 'lab', mimetypes supported are: 
	text/html
```

Thankful for any help,
Cheers

**Comment by betatim** [comment] 2021-04-09 09:46
Could you post which version of jupyter lab you have installed?

**Comment by astronomyk** [comment] 2021-04-09 14:43
I had the same problem today. 
- Python 3.7.2
- jupyter 1.0.0
- nbconvert 6.0.7

I did find an entry in Jupyter notebook which allowed me to export to PDF from the menu ``download as --> PDF via Pyppeteer (.html)``, however it wasn't the same entry name as defined in the setup.py ``entry_point`` (i.e. ``PDFviaHTML``). Does Pyppeteer also provide functionality to download as PDF?

**Comment by betatim** [comment] 2021-04-10 07:14
> Does Pyppeteer also provide functionality to download as PDF?

This package uses pyppeteer to generate the PDF as well :) So I think the answer is yes. I don't know where the second entry "PDF via Pyppeteer" comes from, I suspect it is a new entry directly from nbconvert. A lot of the code and ideas from notebook-as-pdf have found their way into nbconvert as the "webpdf" export option.

I've created #29 which (I think) fixes the problems that occur when using nbconvert 6.x.

**Comment by astronomyk** [comment] 2021-04-11 20:23
Just a note to say that I can confirm your changes in the branch work for nbconvert 6.0.7 
Thanks heaps for enacting this change so quickly! I really appreciate it!

**Comment by 1kastner** [comment] 2021-04-13 15:38
With Windows 10 I faced the same issue, so I guess we can remove `M1 Mac, Big Sur 11.2` from the title of this issue?

**Comment by betatim** [comment] 2021-04-23 14:13
There is a new release (v0.5.0) which should fix the issue. Closing for now, @halloyz if it turns out this isn't fixed with the latest release please reopen.

**Closed by betatim** 2021-04-23 14:13 UTC
